rm -rf test/1-binary/*.hex.txt
rm -rf test/4-reference/*.txt
rm -rf test/2-simulator/mips*
rm -rf test/3-output/*stdout
rm -rf test/0-cases/*r3.txt
rm -rf test/0-cases/*r2.txt
rm -rf test/0-cases/*r1.txt
rm -rf test/0-cases/*r3a.txt
rm -rf test/0-cases/*r2a.txt
rm -rf test/0-cases/*r1a.txt
rm -rf test/0-cases/*r3b.txt
rm -rf test/0-cases/*r2b.txt
rm -rf test/0-cases/*r1b.txt
rm -rf test/6-waveforms/*.vhd
rm -rf test/6-waveforms/*.vcd
rm -rf test/assembler
rm -rf test/test_case_fns
